---
k3s_version: v1.22.3+k3s1
ansible_user: CHANGEME
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik --disable servicelb --disable local-storage --kube-proxy-arg proxy-mode=ipvs"
# extra_server_args: ""
extra_agent_args: ""