ingress-nginx:
  tcp:
    22: "gitea/gitea-ssh:22"
    222: "gitlab/gitlab-gitlab-shell:222"
  controller:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: domain.com.
        metallb.universe.tf/address-pool: default
        cert-manager.io/issuer: "letsencrypt-prod"
      loadBalancerIP: 192.168.x.x
      externalTrafficPolicy: Local 
      externalIPs:
      - x.x.x.x
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  defaultBackend:
    enabled: false
