argo-cd:
  ## Server
  server:
    extraArgs:
      - --insecure
    config:
      statusbadge.enabled: 'true'
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    # service: # for metallb
    #   type: LoadBalancer
    certificate:
      enabled: true
      domain: argo.domain.com
      issuer:
        group: "cert-manager.io"
        kind: "ClusterIssuer"
        name: "letsencrypt-prod"
      secretName: argo-domain-com-tls
    ingress:
      enabled: true
      ingressClassName: "nginx" 
      hosts:
        - argo.domain.com
      paths:
        - /
      tls:
        - secretName: argo-domain-com-tls
          hosts:
            - argo.domain.com
      https: true
