kube-prometheus-stack:
  grafana:
    adminPassword: P@$$word123!
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - grafana.domain.com
      tls:
        - secretName: grafana-domain-com-tls
          hosts:
            - grafana.domain.com
  prometheusOperator:
    admissionWebhooks:
      enabled: false
      certManager:
        enabled: true
